#services:
#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017'


version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pauta


#version: '3.4'
#services:
#  redis:
#    image: redis
#    restart: always
#    ports:
#      - "6379:6379"
#    expose:
#      - "6379"

#  mongodb:
#    image: mongo
#    restart: always
#    ports:
#      - "27017:27017"
#    expose:
#      - "27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=123456
#      - MONGO_INITDB_DATABASE=compasso_db
#    volumes:
#      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

#  mongo-express:
#    image: mongo-express
#    restart: always
#    environment:
#      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
#      - ME_CONFIG_MONGODB_PORT=27017
#      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
#      - ME_CONFIG_MONGODB_AUTH_DATABASE=compasso_db
#      - ME_CONFIG_MONGODB_AUTH_USERNAME=compasso
#      - ME_CONFIG_MONGODB_AUTH_PASSWORD=123456
#      - ME_CONFIG_BASICAUTH_USERNAME=admin
#      - ME_CONFIG_BASICAUTH_PASSWORD=admin
#    depends_on:
#      - mongodb
#    ports:
#      - "8091:8081"
#    expose:
#      - "8081"


#version: "3.7"
#services:
#  api-service:
#    image: spring-boot-mongodb-docker-compose
#    build: .
#    restart: always
#    ports:
#      - 9091:8080
#    depends_on:
#      - api-database
#  api-database:
#    image: "mongo:latest"
#    restart: always
#    ports:
#      - 27017:27017
#

#
#version: "3.7"
#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - mongo_db
#  mongo_db:
#    image: "mongo:4.4.3"
#    restart: always
#    ports:
#      - 27017:27017